before:
  hooks:
#    - go mod download
builds:
  - id: go
    binary: go
    env:
      - CGO_ENABLED=0
    goos:
      - aix
    goarch:
      - ppc64
    ldflags:
      - -X main.Branch={{.Branch}}
      - -X main.Version={{.Version}}
      - -X main.Revision={{.Commit}}
    gcflags:
      # I love errors.
      - -e
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge'
release:
  github:
  name_template: v{{.Version}}
